language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "2.7"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install -r requirements.txt

script:
  - make pytest
  - make test

after_sucess:
  - coveralls
