language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "2.7"
  - "2.6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - py.test --cov=iprofile tests/

after_sucess:
  coveralls
