language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install python-coveralls

script:
  - py.test --cov-config .coveragerc --cov=iprofile tests/

after_sucess: coveralls
